### ISSUE TITLE
Psvita dock doesn't work on pi4 4gb

### ISSUE THREAD

**Issue by AlessandroBaio** [SilentNightx/VitaDockPlus#12]
![photo_2021-03-28_17-06-30](https://user-images.githubusercontent.com/43813210/112757007-05f41900-8fe8-11eb-828d-8f32479ef441.jpg)

When i power on the raspberry i have a black screen after a few seconds...any ideas?

**Comment by bcodemaster** [comment]
![image](https://user-images.githubusercontent.com/17169234/174460767-e9d3af75-a308-4919-b22c-bf5d99b4b801.png)

Hi it seems that SilentNightx didn't optimize the "VitaDock Plus V1.2.img" file for Raspberry Pi 4

Essentially you will need to replace both .DAT and .ELF files with RASPIAN operating system files for Raspberry Pi 4

First delete them on micro SD those files and then paste the ones from RASPIAN for Pi 4

**Comment by SilentNightx** [comment]
Issue resolved in latest image.
