### ISSUE TITLE
Case/ Button/ IR Compatability

### ISSUE THREAD

**Issue by urkman5000** [SilentNightx/VitaDockPlus#14]
Hey there set up Vitadock+ easily and running smoothly. Using a 3b+ and piboxy Case.
The piboxy Case features an IR Remote an Power & Reset Buttons.
When i try to install their addon/package through terminal with -> run termit it not seems to be installed completetly.
Wanna do a save shutdown/boot with the IR Remote of the Case if possible. Is there any Chance to get it to work?

script is

curl -sSL piboxy.com/install | bash

if someone wants to test it

**Comment by SilentNightx** [comment]
Would be better to ask the Piboxy Team.
