### ISSUE TITLE
PSVITA CUSTOM USB WIRE

### ISSUE THREAD

**Issue by Snake-Programerlod** [SilentNightx/VitaDockPlus#15]
Hello, first of all a great project your version of VitaDock and thank you very much for sharing it.

I have a problem, I just made a shorter cable to connect my psvita to the dock, however it does not give me an image on the vitadock, it is worth mentioning that I tested the cable directly on the computer in the obs connecting the psvita via usb and if It gave an image, so I don't know what to do if it didn't work, not even on the computer. I would say that I did the cable wrong, but if it works on the computer and not on the vitadock+, I don't know if you know of any restrictions in this regard, I have another cable that I haven't altered in the least but this works without problems I hope you can guide me now if I don't know what's wrong.

**Comment by SilentNightx** [comment]
Interesting. Only suggestion I have is to try the latest image as connectivity is improved on it.
