### ISSUE TITLE
(suggestion if posible) connect audio to the 3.5mm jack on rpi?

### ISSUE THREAD

**Issue by alfredox123** [SilentNightx/VitaDockPlus#17]
Is it possible to connect the 3.5 mm jack on the ps vita to the one that has the rpi and reroute audio to hdmi? or is something that cant be done?.

I was thinking on this idea because audio through bluetooth has huge delay compared to the direct 3.5mm jack audio.

**Comment by SilentNightx** [comment]
Raspberry Pi 3.5mm jacks don't accept input. They are only for output. You could use a USB adapter for this functionality though.

**Comment by alfredox123** [comment]
could you give me an adapter suggestion? do i need to modify something on rpi or ps vita for this to work or should work out of the box?
