### ISSUE TITLE
raspberry pi 4

### ISSUE THREAD

**Issue by Raulking868** [SilentNightx/VitaDockPlus#18]
i can't connect with ps vita ul to bluetooth. gives me connection error.

**Comment by bcodemaster** [comment]
It seems on SilentNightx "VitaDock Plus V1.2.img" it wasn't necessary for Raspberry Pi 4

So you will need to connect a keyboard and go to RUN and write TERMIT to launch the terminal.

In the terminal you will need to type following code to update the bluetooth:

sudo apt install bluetooth pi-bluetooth bluez blueman

Link for help: https://howchoo.com/pi/bluetooth-raspberry-pi

**Comment by SilentNightx** [comment]
Should be resolved on the latest image.
