### ISSUE TITLE
Bluetooth audio connected but no sound from TV

### ISSUE THREAD

**Issue by NayoMays** [SilentNightx/VitaDockPlus#2]
Title explains the issue, please let me know what info I should supply. Thanks!

**Comment by DerpyBubblez** [comment]
This is also an issue for me on my RasPi 3B+

**Comment by SilentNightx** [comment]
Please try the new image. Also make sure the Vita is showing as connected in the Bluetooth menu and HDMI sound output is selected in the audio menu on the dock.
