### ISSUE TITLE
Flash image failed

### ISSUE THREAD

**Issue by Snake-Programerlod** [SilentNightx/VitaDockPlus#20]
I try to flash your img ver. 2.0, with balena etcher but when validating image, return failed

when flash your img ver. 1.2 dont have problems

my raspberry model is 3b+

could you helpme with this issue.

**Comment by SilentNightx** [comment]
Try using the Raspberry Pi Imager instead of Balena.

**Comment by Snake-Programerlod** [comment]
Thanks bro, i will check...
