### ISSUE TITLE
Bluetooth audio issues

### ISSUE THREAD

**Issue by Stonners23** [SilentNightx/VitaDockPlus#21]
Thanks for the updated version - loving all the updates.  Using a rasp pi 3b and can link to bluetooth, but no audio comes through to TV.  Have amended audio settings to HDMI out, but Vita device options defaults to off, no matter how many times I change to one of the 3 options there.  Help?

**Comment by Snake-Programerlod** [comment]
I have the same issue that @Stonners23, my raspberry pi is the same model to, when select High Fidelity Capture, if is paried to vita, the conection was aborted, and when pairing again the High Fidelity change to off, i hope could you help us

**Comment by SilentNightx** [comment]
Please try the legacy image I just uploaded and report back. Also please provide your specific model and revision using the instructions on the GitHub readme.

**Comment by Stonners23** [comment]
Great stuff thanks.  Installed and all seems to be working as it should :)

**Comment by SilentNightx** [comment]
Due to these issues I've rolled back some changes. The image that caused this issue is now labeled experimental and the legacy image is the new main image.
