### ISSUE TITLE
about bluetooth

### ISSUE THREAD

**Issue by Northwemko** [SilentNightx/VitaDockPlus#22]
pi 2b
psvita 1000
usb csr8510 bluetooth adapter

bluetooth can connect to vita ,but no sound,if use 1.2,no problem,It seems that there is a problem with the compatibility of the new version of Bluetooth

**Comment by SilentNightx** [comment]
Try legacy image and report back with specific model and revision using the instructions in the GitHub readme.

**Comment by Northwemko** [comment]
> I rolled back some updates. Image you tried is now labeled as experimental due to these issues. Please try reflashing the current image.

later, i'll try,can u add img MD5 hash?  and can u add usb-hub functions?
