### ISSUE TITLE
No audio through HDMI even with Bluetooth correctly paired

### ISSUE THREAD

**Issue by dantesquivel** [SilentNightx/VitaDockPlus#23]
I have successfully paired the Vita to the Vitadock. To get Playstation Vita to show up in the right click Pulse Audio options in the bottom right I have to set the analog and hdmi and playstation vita in the profiles to off and then turn on the playstation vita to playback (A2DP) I believe. The volume on the Vita will act up for a bit showing mute and I have to physically turn it back on, but eventually I can see Playstation Vita as checked with green in pulse audio in the Vitadock and VitaDock + with green dot in the vita. There's just no sound. 

Things I've tried:
- I always check that the volume is up on the Vita itself
- 2 different TVs with hdmi audio (a computer monitor and a projector through a AV amp)
- I have tried 2 different vitas modded with henkaku 3.65
- I have tried 2 different Raspberry Pis 4 with 8G
- Different hdmi cables
- uninstalling virtually all plugins except the one needed to dock the vita
- both the current and experimental image (I have re flashed the current version 2) in different sd cards
- all possible combinations of resetting both vita and vitadock throughout the process
- a bluetooth dongle rather than the internal bluetooth

Still get no audio through hdmi. Everything else either works like a charm or I've found a work around.

Other observations:
- Should the VitaDock+ bluetooth device in the vita have the speaker icon next to it, just like bluetooth headphones? because it doesn't
- It does seem like a problem that I have to toggle settings in pulse audio to get the Playstation to appear under Analog and HDMI, it doesn't seem to happen on its own
- When everything is connected, sometimes the volume rocker on the vita will show the on screen volume bars with the bluetooth icon at the end sometimes not

Thanks for all your work on this!

**Comment by SilentNightx** [comment]
Should be fixed in V2.5 thanks for the detailed information about the issue.
