### ISSUE TITLE
[Feature Request] Install Script for Existing RPiOS

### ISSUE THREAD

**Issue by andynameistaken** [SilentNightx/VitaDockPlus#27]
Hi could you write script for configuring existing RPiOS?

**Comment by SilentNightx** [comment]
You could follow the instructions in the [Developer Wiki](https://github.com/SilentNightx/VitaDockPlus/wiki) to achieve this or you can use this [script](https://github.com/butstevetho/vitadock-pi4-installer) although it might be outdated.
