### ISSUE TITLE
[Feature Request] 480x272 at 30fps mode (i.e. improved Pi Zero 1 support due to Pi Zero 2 shortage)

### ISSUE THREAD

**Issue by padraigfl** [SilentNightx/VitaDockPlus#29]
Given the shortage of Pi Zero 2 (expected to continue into Spring 2023 last I've heard) and everything Pi 4 related in the world at the moment I had a look at the potential value of reviving Pi Zero support a bit as there's tons of them lying around the place. As [Vita-UDCD-UVC](https://github.com/xerpi/vita-udcd-uvc) supports a lower resolution option I decided to see what would happen if I modified the scripts to use that option instead (480x272 at 30fps). 

Here are the results compared against the standard 30fps option:
https://user-images.githubusercontent.com/14135877/200130785-2a88f113-e142-4219-a7ec-13ce524bf827.MOV
https://user-images.githubusercontent.com/14135877/200130801-d7850fdc-b5cd-4208-a04e-57d06d7bcc56.MOV

In both videos /boot/config.txt had the following and I was running in low-latency mode:
- arm_freq: 1000
- core_freq: 450
- over_voltage: 6

Tried playing some Lumines on it and the latency was enough to be annoying but I think the speed gains tip it into playable status for most games. Obviously playing at 50% resolution causes big issues for text on Vita games but most emulated games should look fine and PSP games should be okay too.

I did not notice major differences in performance between low latency mode and normal mode at this resolution and I'm currently not able to check whether bluetooth audio would impact performance.

One issue I seemed to encounter was that my Vita (OLED) wasn't getting enough power from the zero to connect (yet it did when I used a USB hub that was powered from the Zero???)

**Comment by SilentNightx** [comment]
Thanks for the suggestion and a good idea but I don't think I'll make it an official feature. 50% resolution is too much of a compromise imo. Don't remember which image but one of the older images was able to get 60 FPS on a Pi Zero with full resolution, was probably the first or second release of VitaDock+. One day we might be able to do that again now that fixes for other Pis are finished.
