### ISSUE TITLE
issue with MEGA download quota

### ISSUE THREAD

**Issue by harmadiwibowo** [SilentNightx/VitaDockPlus#30]
Hi, can you give us download option that can be downloaded free without quota, since MEGA just give us 3GB quota and we must wait for 5 hours ++ to wait until the quota is back to normal. Thank you.

**Comment by andypoo79** [comment]
Hi, is it possible to provide another download link please?

I would love to try this project ut cannot access it via Mega 

many thanks

**Comment by pslawx** [comment]
Hi, I also would love to try it, but MEGA with free quota usage is not the ideal place, could you please upload on Google Drive or some other place that let us to download? Or if possible give us a tutorial showing how to build this image on our own machines. Thanks a lot!

**Comment by SilentNightx** [comment]
Added another download option to the new release. If anyone wants to help host a torrent let me know.
