### ISSUE TITLE
Disable Bluetooth SAP plugin

### ISSUE THREAD

**Issue by francoisjacques** [SilentNightx/VitaDockPlus#38]
In the bluetoothd log, we can see entries with:

```
sap-server: Operation not permitted 
``` 

It's easy to fix adding an override file. See https://raspberrypi.stackexchange.com/a/99920

**Comment by SilentNightx** [comment]
Fixed in V2.6 image. Won't include in source files since it's likely an underlying Raspberry Pi OS issue.
