### ISSUE TITLE
Unable to open aux configuration tool

### ISSUE THREAD

**Issue by ghost** [SilentNightx/VitaDockPlus#40]
So I was having some issues with my raspberry pi 4 vita dock, and reflashed the image just to be safe (this didn't help) and now, even after trying to open the configuration to a manually via the PlayStation button, no window pops up for me to configure the auxiliary, not even on the "first" connection after reflashing.

**Comment by Ninjajoe95** [comment]
Not sure how, but reflashing it onto a different card fixed it just fine-

**Comment by SilentNightx** [comment]
Fixed in V2.6.
