### ISSUE TITLE
Heat dissipation with GPIO

### ISSUE THREAD

**Issue by francoisjacques** [SilentNightx/VitaDockPlus#44]
Triggering BT discovery through GPIO is nifty, but I've found that having this enabled makes the pi run very hot for little use. 

Until there's another way not involving eager polling, I think that by default it should perhaps be disabled? Whoever wants to tinker with GPIO should have all the knowledge to change the config file.

EDIT: changing the [vitadock.conf](https://github.com/SilentNightx/VitaDockPlus/blob/main/home/pi/vitadock.conf#L14) from

```
DISCOVERY_KEY_GPIO=5
```

to

```
# DISCOVERY_KEY_GPIO=5
```

**Comment by SilentNightx** [comment]
Proper fix in V2.6.
