### ISSUE TITLE
Stream freezing Vita 1000 on RPI 3 B+

### ISSUE THREAD

**Issue by ArcheoCodix** [SilentNightx/VitaDockPlus#46]
Hello,

When I connect my vita, the stream appears and after 2-5 seconds, the video freezes and the vita disconnects after 1 min.
With the --log-file option, I get this log several times: 
`Dequeued v4l2 buffer contains corrupted data (0 bytes)`
In journalctl, I get this line:
`uvcvideo non-zero status (-71) in video completion handler`

VitaDock+ is installed on a RPI 3 B+ and I have a PSVita 1000.

I tried under windows with PSVitaPlay, it works.

Thanks for your help.

**Comment by ArcheoCodix** [comment]
Are there any logs that could help you understand the problem ?
Let me know and I'll try to provide you with any information or perform any manipulation.

**Comment by SilentNightx** [comment]
@ArcheoCodix It's quite difficult for me to debug issues on Pis I don't own unfortunately.

That being said there's been a lot of users report Pi 3 B+ working perfectly.

So my suggestion is to:
1. Use latest VitaDock+ image.
2. Try a different cable.
3. Try a different port.
4. Try a different Pi power supply.
5. Make sure you are using latest official Xerpi plugin.

Let me know if you are still having issues after that. Thanks.

**Comment by ArcheoCodix** [comment]
I tried with version 2.6, but the problem persists.
I'm using a Kubii power cable designed for RPI 3.
I don't have an official Vita cable anymore, I'll try to find one to order.
Do you have any to recommend ?

**Comment by ArcheoCodix** [comment]
Hi,
In the end, it was my PS Vita cable that was the problem.
An official cable works, maybe an unofficial one works and it was my cable that was faulty, I wouldn't know.
Thanks for your help.

It's a good project, a little extra idea would be a video processing by RPI to increase its resolution for example.
To be seen on more powerful SBCs.
