### ISSUE TITLE
Missing HOWTO to create a new image 

### ISSUE THREAD

**Issue by francoisjacques** [SilentNightx/VitaDockPlus#47]
For contributors, it would be wonderful to have at least some sort of HOWTO on which distro is used as baseline and what files needs to be copied (+ rwx attributes, owner) where in order to produce a new image.

From these instructions, some automation could then be developed to build customized/development images.

**Comment by SilentNightx** [comment]
@francoisjacques That's what the wiki is for :). Note there will likely be some permissions errors not covered by the initial chmod, need to figure out what they are if any and update it.

https://github.com/SilentNightx/VitaDockPlus/wiki
